spring.application.name=foodify-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/foodify
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true